### ISSUE TITLE
无法通过说明文档中的步骤正确启动项目

### ISSUE THREAD

**Issue by HyperClockUp** [noomijs/noomi#6]
发现使用noomi-cli -n 方式创建noomi项目后，目录下package.json文件与readme.md文件中依赖包不相同
```
{
  "name": "myApp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "mysql": "^2.17.1",
    "mysql2": "^2.0.1",
    "noomi": "^0.1.6"
  }
}

```

手动使用npm install json5 ……之后依赖报错问题解决

在vscode界面按下F5之后出现
![图片](https://user-images.githubusercontent.com/36909196/69472689-4c2fdb80-0de8-11ea-8764-6c43f8cc9706.png)

使用ts-node app.ts 后出现以下报错信息
```
$ ts-node app.ts
Server is startup ...
web初始化...
web初始化完成！
实例工厂初始化...
(node:10122) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/code/forTest/noomiTest/myApp//dist/module'
    at Object.readdirSync (fs.js:870:3)
    at handleDir (/code/forTest/noomiTest/myApp/node_modules/noomi/dist/core/main/instancefactory.js:292:46)
    at Function.addInstances (/code/forTest/noomiTest/myApp/node_modules/noomi/dist/core/main/instancefactory.js:285:17)
    at /code/forTest/noomiTest/myApp/node_modules/noomi/dist/core/main/instancefactory.js:258:26
    at Array.forEach (<anonymous>)
    at Function.handleJson (/code/forTest/noomiTest/myApp/node_modules/noomi/dist/core/main/instancefactory.js:256:28)
    at Function.parseFile (/code/forTest/noomiTest/myApp/node_modules/noomi/dist/core/main/instancefactory.js:222:14)
    at Function.init (/code/forTest/noomiTest/myApp/node_modules/noomi/dist/core/main/instancefactory.js:13:18)
    at Noomi.init (/code/forTest/noomiTest/myApp/node_modules/noomi/dist/core/main/noomi.js:84:47)
    at new Noomi (/code/forTest/noomiTest/myApp/node_modules/noomi/dist/core/main/noomi.js:23:14)
    at Object.noomi (/code/forTest/noomiTest/myApp/node_modules/noomi/dist/core/main/noomi.js:174:12)
    at Object.<anonymous> (/code/forTest/noomiTest/myApp/app.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:530:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:533:12)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)
    at main (/usr/local/lib/node_modules/ts-node/src/bin.ts:212:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/src/bin.ts:470:3)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
(node:10122) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10122) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

目录结构如下
![图片](https://user-images.githubusercontent.com/36909196/69472723-c2ccd900-0de8-11ea-8296-3c82f3fe685e.png)

请问是否是我使用方式不正确导致的错误内容，请劳烦告知正确使用姿势

**Comment by fieldyang** [comment]
已经在noomi包中加入了官方文档的依赖包，noomi-cli带的依赖包是非必要包，为sequelize + mysql时需要的，为初学者准备，没有打入noomi中。cli安装后，macos 和 win10测试过，都可以正常运行，我下午清理所有环境后再测试一遍，会及时更新到该issue中。

**Comment by fieldyang** [comment]
经过测试，发现实例模块加载时的确多了一个"/"，但是实测过程中，macos和windows10都可以正常加载模块，新noomi包已提交，清空之前项目的目录，重新执行noomi-cli -n 即可。
但是看你的错误提示，可能存在路径大小写问题。新建一个目录，该目录空白即可，然后执行 noomi-cli -n，不需要修改任何文件。用ts-node app.ts运行或vscode运行（workspace 加入该目录，找到app.ts，直接f5即可）都可以。如果还是报错，请加qq群，把你的文件夹压缩后发群里（qq群号在issue 2），我帮你看看。

**Comment by fieldyang** [comment]
已在centos7下测试过，如果采用ts-node 运行，在ts-node app.ts之前，运行 npm run build 对module目录下的ts文件进行编译，npm noomi-cli 已更新，请查看npm noomi-cli readme

**Comment by HyperClockUp** [comment]
使用方法二成功运行～
